# ---- CN Project teamX : Mac 2 edge ----
log_format teamX_lb '$remote_addr [$time_local] "$request" $status -> upstream=$upstream_addr ($upstream_status) $request_time s';

upstream teamX_backends {
    # round-robin is nginx's default strategy
    server 10.7.18.190:3001 max_fails=1 fail_timeout=10s;   # Backend A (Trishit)
    server 10.7.24.166:3002 max_fails=1 fail_timeout=10s;   # Backend B (Husain)
}

# plain HTTP -> redirect to HTTPS
server {
    listen 80;
    server_name app.teamX.test api.teamX.test;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;                     # use 8443 if 443 won't bind
    http2 on;
    server_name app.teamX.test api.teamX.test;

    ssl_certificate     /Users/sarveshsrinath/cn-project/tls/app.teamX.test.crt;
    ssl_certificate_key /Users/sarveshsrinath/cn-project/tls/app.teamX.test.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /opt/homebrew/var/log/nginx/teamX_access.log teamX_lb;

    location / {
        proxy_pass http://teamX_backends;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
        proxy_next_upstream error timeout http_502 http_503;   # retry the other backend if one is down
        add_header X-Edge "mac2-nginx" always;
        add_header X-Upstream-Addr $upstream_addr always;      # shows which backend IP:port served you
    }
}
